---
- name: network backup playbook
  hosts: network
#  connection: network_cli
  gather_facts: no

  collections:
    - cisco.ios
  
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios


  tasks:
    - name: "Backup Cisco ios configuration"
      cisco.ios.ios_config:
        backup: yes
        backup_options:
          filename: "backup.cfg"
          dir_path: /tmp/
      register: ciscocfg
      when: ansible_network_os == 'cisco.ios.ios'

    - name: "Create backup dest dir if it doesnt exist"
      ansible.builtin.file:
        path: /tmp/backup
        state: directory
      delegate_to: backup-server
      become: true
      run_once: true

    - name: debug ciscocfg
      debug:
        msg:
        - "{{ ciscocfg }}"


    - name: "Copy config to remote backup server"
      copy:
#        src: "{{ ciscocfg.backup_path }}"
        src: "/tmp/backup.cfg"
        dest: "/tmp/backup/cisco/"
      when: ciscocfg is defined
      delegate_to: backup-server
      become: true
      
   
       
