---
- name: network restore playbook
  hosts: network
  gather_facts: false

  collections:
    - cisco.ios

#  vars:
#    ansible_connection: ansible.netcommon.network_cli
#    ansible_network_os: cisco.ios.ios

  tasks:
    - name: retreive configuration from backup-server to execution environment
      ansible.builtin.fetch:
        src: "/tmp/backup/cisco/{{ rollback_date }}/{{ inventory_hostname }}.txt"
        dest: "/tmp/{{ rollback_date }}/"
        flat: true
      delegate_to: backup-server
      when: ansible_network_os is defined


    - name: print file being restored
      ansible.builtin.debug:
        msg: "restoring from /tmp/backup/cisco/{{ rollback_date }}/{{ inventory_hostname }}.txt"

#    - name: Include task list in play
#      ansible.builtin.include_tasks: "ios/{{ restore_mode | default('merge') }}.yml"

    - name: restore the config with merge config
      cisco.ios.ios_config:
        src: "/tmp/{{ rollback_date }}/{{ inventory_hostname }}.txt"
      when: ansible_network_os is defined

    - name: print to terminal window
      ansible.builtin.debug:
        msg: |
          "Restore is complete for device {{ inventory_hostname }}
          is set to {{ rollback_date }} timestamp,
          restored with restore_mode {{ restore_mode | default('merge') }}"
