---
- name: network backup playbook
  hosts: network
  gather_facts: false

  collections:
    - cisco.ios

#  vars:
  ## network devices host details variables
#    ansible_connection: ansible.netcommon.network_cli
#    ansible_network_os: cisco.ios.ios
#    ansible_user: "ansible"
#    ansible_become: "true"
#    ansible_become_method: "true"

  ## backup server host details variables
#    ansible_user: "userbackup"
#    ansible_password: "remotepassword"
#    ansible_become_password: "xyz"


  tasks:
    - name: "Backup Cisco ios configuration"
      cisco.ios.ios_config:
        backup: true
        backup_options:
          filename: "backup.cfg"
          dir_path: /tmp/
      register: ciscocfg
#      when: ansible_network_os == 'cisco.ios.ios'
      when: ansible_network_os is defined

    - name: "Create backup dest dir if it doesnt exist"
      ansible.builtin.file:
        path: /tmp/backup/cisco
        state: directory
      delegate_to: backup-server
      become: true
      run_once: true
      register: ciscopath

    - name: "Remove non config lines (Building config)"
      ansible.builtin.lineinfile:
        path: "{{ ciscocfg.backup_path }}"
        line: "Building configuration..."
        state: absent
      delegate_to: localhost

#    - name: debug ciscocfg
#      debug:
#        msg:
#        - "{{ ciscocfg }}"

    - name: "Create time stamp for play"
      ansible.builtin.set_fact:
        datetime: "{{ lookup('pipe','date +%Y-%m-%d-%H-%M') }}"
      delegate_to: backup-server
      delegate_facts: true
      run_once: true


    - name: "Copy config to remote backup server"
      ansible.builtin.copy:
        src: "{{ ciscocfg.backup_path }}"
        dest: "/tmp/backup/cisco/{{ hostvars['backup-server'].datetime }}/"
#      src: "/tmp/backup.cfg"
#      dest: "/tmp/backup/cisco/"
      when: ciscocfg is defined
      delegate_to: backup-server
      become: true
